# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project Filter2DKernel
set_top Filter2DKernel
add_files "/home/centos/SME-Developer-Labs/module_02/filter2d/workspace/Filter2D/src/kernel/filter2d.cpp" -cflags " -g -I /home/centos/SME-Developer-Labs/module_02/filter2d/workspace/Filter2D/src/kernel"
add_files "/home/centos/SME-Developer-Labs/module_02/filter2d/workspace/Filter2D/src/kernel/axi2stream.cpp" -cflags " -g -I /home/centos/SME-Developer-Labs/module_02/filter2d/workspace/Filter2D/src/kernel"
open_solution solution_OCL_REGION_0
set_part xcvu9p-flgb2104-2-i
create_clock -period 250MHz -name default
set_clock_uncertainty 1.080000
config_rtl -register_reset
config_rtl -stall_sig_gen
config_interface -m_axi_addr64
config_schedule -relax_ii_for_timing
config_compile -pipeline_loops 64
config_compile -name_max_length 256
csynth_design
export_design -format ipxact -kernel_drc -sdaccel
close_project
puts "Vivado HLS completed successfully"
exit
