// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Filter2DKernel,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.920000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=78,HLS_SYN_DSP=904,HLS_SYN_FF=60137,HLS_SYN_LUT=38112}" *)

module Filter2DKernel (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        stall_start_ext,
        stall_done_ext,
        stall_start_str,
        stall_done_str,
        stall_start_int,
        stall_done_int
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 256;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (256 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (256 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   stall_start_ext;
output   stall_done_ext;
output   stall_start_str;
output   stall_done_str;
output   stall_start_int;
output   stall_done_int;

reg stall_start_ext;
reg stall_done_ext;
reg stall_start_str;
reg stall_done_str;
reg stall_start_int;
reg stall_done_int;

reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [63:0] coeffs;
wire   [63:0] src_V;
wire   [31:0] width;
wire   [31:0] height;
wire   [31:0] stride;
wire   [63:0] dst_V;
wire    gmem1_AWREADY;
wire    gmem1_WREADY;
wire    gmem1_ARREADY;
wire    gmem1_RVALID;
wire   [255:0] gmem1_RDATA;
wire    gmem1_RLAST;
wire   [0:0] gmem1_RID;
wire   [0:0] gmem1_RUSER;
wire   [1:0] gmem1_RRESP;
wire    gmem1_BVALID;
wire   [1:0] gmem1_BRESP;
wire   [0:0] gmem1_BID;
wire   [0:0] gmem1_BUSER;
wire    gmem0_AWREADY;
wire    gmem0_WREADY;
wire    gmem0_ARREADY;
wire    gmem0_RVALID;
wire   [255:0] gmem0_RDATA;
wire    gmem0_RLAST;
wire   [0:0] gmem0_RID;
wire   [0:0] gmem0_RUSER;
wire   [1:0] gmem0_RRESP;
wire    gmem0_BVALID;
wire   [1:0] gmem0_BRESP;
wire   [0:0] gmem0_BID;
wire   [0:0] gmem0_BUSER;
wire    AXIBursts2PixelStream8_U0_ap_start;
wire    AXIBursts2PixelStream8_U0_ap_done;
wire    AXIBursts2PixelStream8_U0_ap_continue;
wire    AXIBursts2PixelStream8_U0_ap_idle;
wire    AXIBursts2PixelStream8_U0_ap_ready;
wire    AXIBursts2PixelStream8_U0_m_axi_axi_V_AWVALID;
wire   [63:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWADDR;
wire   [0:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWID;
wire   [31:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWLEN;
wire   [2:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWSIZE;
wire   [1:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWBURST;
wire   [1:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWLOCK;
wire   [3:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWCACHE;
wire   [2:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWPROT;
wire   [3:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWQOS;
wire   [3:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWREGION;
wire   [0:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_AWUSER;
wire    AXIBursts2PixelStream8_U0_m_axi_axi_V_WVALID;
wire   [255:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_WDATA;
wire   [31:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_WSTRB;
wire    AXIBursts2PixelStream8_U0_m_axi_axi_V_WLAST;
wire   [0:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_WID;
wire   [0:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_WUSER;
wire    AXIBursts2PixelStream8_U0_m_axi_axi_V_ARVALID;
wire   [63:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARADDR;
wire   [0:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARID;
wire   [31:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARLEN;
wire   [2:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARSIZE;
wire   [1:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARBURST;
wire   [1:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARLOCK;
wire   [3:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARCACHE;
wire   [2:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARPROT;
wire   [3:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARQOS;
wire   [3:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARREGION;
wire   [0:0] AXIBursts2PixelStream8_U0_m_axi_axi_V_ARUSER;
wire    AXIBursts2PixelStream8_U0_m_axi_axi_V_RREADY;
wire    AXIBursts2PixelStream8_U0_m_axi_axi_V_BREADY;
wire   [7:0] AXIBursts2PixelStream8_U0_stream_V_din;
wire    AXIBursts2PixelStream8_U0_stream_V_write;
wire   [31:0] AXIBursts2PixelStream8_U0_width_out_din;
wire    AXIBursts2PixelStream8_U0_width_out_write;
wire   [31:0] AXIBursts2PixelStream8_U0_height_out_din;
wire    AXIBursts2PixelStream8_U0_height_out_write;
wire   [31:0] AXIBursts2PixelStream8_U0_stride_out_din;
wire    AXIBursts2PixelStream8_U0_stride_out_write;
wire   [63:0] AXIBursts2PixelStream8_U0_coeffs_out_din;
wire    AXIBursts2PixelStream8_U0_coeffs_out_write;
wire   [63:0] AXIBursts2PixelStream8_U0_dst_V_out_din;
wire    AXIBursts2PixelStream8_U0_dst_V_out_write;
wire    AXIBursts2PixelStream8_U0_ap_ext_blocking_n;
wire    AXIBursts2PixelStream8_U0_ap_str_blocking_n;
wire    AXIBursts2PixelStream8_U0_ap_int_blocking_n;
wire    Filter2D_U0_ap_start;
wire    Filter2D_U0_ap_done;
wire    Filter2D_U0_ap_continue;
wire    Filter2D_U0_ap_idle;
wire    Filter2D_U0_ap_ready;
wire    Filter2D_U0_m_axi_srcCoeffs_AWVALID;
wire   [63:0] Filter2D_U0_m_axi_srcCoeffs_AWADDR;
wire   [0:0] Filter2D_U0_m_axi_srcCoeffs_AWID;
wire   [31:0] Filter2D_U0_m_axi_srcCoeffs_AWLEN;
wire   [2:0] Filter2D_U0_m_axi_srcCoeffs_AWSIZE;
wire   [1:0] Filter2D_U0_m_axi_srcCoeffs_AWBURST;
wire   [1:0] Filter2D_U0_m_axi_srcCoeffs_AWLOCK;
wire   [3:0] Filter2D_U0_m_axi_srcCoeffs_AWCACHE;
wire   [2:0] Filter2D_U0_m_axi_srcCoeffs_AWPROT;
wire   [3:0] Filter2D_U0_m_axi_srcCoeffs_AWQOS;
wire   [3:0] Filter2D_U0_m_axi_srcCoeffs_AWREGION;
wire   [0:0] Filter2D_U0_m_axi_srcCoeffs_AWUSER;
wire    Filter2D_U0_m_axi_srcCoeffs_WVALID;
wire   [255:0] Filter2D_U0_m_axi_srcCoeffs_WDATA;
wire   [31:0] Filter2D_U0_m_axi_srcCoeffs_WSTRB;
wire    Filter2D_U0_m_axi_srcCoeffs_WLAST;
wire   [0:0] Filter2D_U0_m_axi_srcCoeffs_WID;
wire   [0:0] Filter2D_U0_m_axi_srcCoeffs_WUSER;
wire    Filter2D_U0_m_axi_srcCoeffs_ARVALID;
wire   [63:0] Filter2D_U0_m_axi_srcCoeffs_ARADDR;
wire   [0:0] Filter2D_U0_m_axi_srcCoeffs_ARID;
wire   [31:0] Filter2D_U0_m_axi_srcCoeffs_ARLEN;
wire   [2:0] Filter2D_U0_m_axi_srcCoeffs_ARSIZE;
wire   [1:0] Filter2D_U0_m_axi_srcCoeffs_ARBURST;
wire   [1:0] Filter2D_U0_m_axi_srcCoeffs_ARLOCK;
wire   [3:0] Filter2D_U0_m_axi_srcCoeffs_ARCACHE;
wire   [2:0] Filter2D_U0_m_axi_srcCoeffs_ARPROT;
wire   [3:0] Filter2D_U0_m_axi_srcCoeffs_ARQOS;
wire   [3:0] Filter2D_U0_m_axi_srcCoeffs_ARREGION;
wire   [0:0] Filter2D_U0_m_axi_srcCoeffs_ARUSER;
wire    Filter2D_U0_m_axi_srcCoeffs_RREADY;
wire    Filter2D_U0_m_axi_srcCoeffs_BREADY;
wire    Filter2D_U0_srcCoeffs_offset_read;
wire    Filter2D_U0_srcImg_V_read;
wire    Filter2D_U0_width_read;
wire    Filter2D_U0_height_read;
wire   [7:0] Filter2D_U0_dstImg_V_din;
wire    Filter2D_U0_dstImg_V_write;
wire   [31:0] Filter2D_U0_width_out_din;
wire    Filter2D_U0_width_out_write;
wire   [31:0] Filter2D_U0_height_out_din;
wire    Filter2D_U0_height_out_write;
wire    Filter2D_U0_ap_ext_blocking_n;
wire    Filter2D_U0_ap_str_blocking_n;
wire    Filter2D_U0_ap_int_blocking_n;
reg    PixelStream2AXIBursts_U0_ap_start;
wire    PixelStream2AXIBursts_U0_ap_done;
wire    PixelStream2AXIBursts_U0_ap_continue;
wire    PixelStream2AXIBursts_U0_ap_idle;
wire    PixelStream2AXIBursts_U0_ap_ready;
wire    PixelStream2AXIBursts_U0_stream_V_read;
wire    PixelStream2AXIBursts_U0_width_read;
wire    PixelStream2AXIBursts_U0_height_read;
wire    PixelStream2AXIBursts_U0_stride_read;
wire    PixelStream2AXIBursts_U0_m_axi_aximm_V_AWVALID;
wire   [63:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWADDR;
wire   [0:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWID;
wire   [31:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWLEN;
wire   [2:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWSIZE;
wire   [1:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWBURST;
wire   [1:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWLOCK;
wire   [3:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWCACHE;
wire   [2:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWPROT;
wire   [3:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWQOS;
wire   [3:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWREGION;
wire   [0:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_AWUSER;
wire    PixelStream2AXIBursts_U0_m_axi_aximm_V_WVALID;
wire   [255:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_WDATA;
wire   [31:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_WSTRB;
wire    PixelStream2AXIBursts_U0_m_axi_aximm_V_WLAST;
wire   [0:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_WID;
wire   [0:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_WUSER;
wire    PixelStream2AXIBursts_U0_m_axi_aximm_V_ARVALID;
wire   [63:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARADDR;
wire   [0:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARID;
wire   [31:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARLEN;
wire   [2:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARSIZE;
wire   [1:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARBURST;
wire   [1:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARLOCK;
wire   [3:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARCACHE;
wire   [2:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARPROT;
wire   [3:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARQOS;
wire   [3:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARREGION;
wire   [0:0] PixelStream2AXIBursts_U0_m_axi_aximm_V_ARUSER;
wire    PixelStream2AXIBursts_U0_m_axi_aximm_V_RREADY;
wire    PixelStream2AXIBursts_U0_m_axi_aximm_V_BREADY;
wire    PixelStream2AXIBursts_U0_aximm_V_offset_read;
wire    PixelStream2AXIBursts_U0_ap_ext_blocking_n;
wire    PixelStream2AXIBursts_U0_ap_str_blocking_n;
wire    PixelStream2AXIBursts_U0_ap_int_blocking_n;
wire    ap_sync_continue;
wire    src_pixels_V_full_n;
wire   [7:0] src_pixels_V_dout;
wire    src_pixels_V_empty_n;
wire    width_c_full_n;
wire   [31:0] width_c_dout;
wire    width_c_empty_n;
wire    height_c_full_n;
wire   [31:0] height_c_dout;
wire    height_c_empty_n;
wire    stride_c_full_n;
wire   [31:0] stride_c_dout;
wire    stride_c_empty_n;
wire    coeffs_c_full_n;
wire   [63:0] coeffs_c_dout;
wire    coeffs_c_empty_n;
wire    dst_V_c_full_n;
wire   [63:0] dst_V_c_dout;
wire    dst_V_c_empty_n;
wire    dst_pixels_V_full_n;
wire   [7:0] dst_pixels_V_dout;
wire    dst_pixels_V_empty_n;
wire    width_c1_full_n;
wire   [31:0] width_c1_dout;
wire    width_c1_empty_n;
wire    height_c2_full_n;
wire   [31:0] height_c2_dout;
wire    height_c2_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Filter2D_U0_ap_ready;
wire    ap_sync_Filter2D_U0_ap_ready;
reg   [1:0] Filter2D_U0_ap_ready_count;
reg    ap_sync_reg_AXIBursts2PixelStream8_U0_ap_ready;
wire    ap_sync_AXIBursts2PixelStream8_U0_ap_ready;
reg   [1:0] AXIBursts2PixelStream8_U0_ap_ready_count;
wire    AXIBursts2PixelStream8_U0_start_full_n;
wire    AXIBursts2PixelStream8_U0_start_write;
wire    Filter2D_U0_start_full_n;
wire    Filter2D_U0_start_write;
wire    PixelStream2AXIBursts_U0_start_full_n;
wire    PixelStream2AXIBursts_U0_start_write;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_int_blocking_cur_n;
wire    ap_ext_blocking_sub_n;
wire    ap_str_blocking_sub_n;
wire    ap_int_blocking_sub_n;
wire    ap_ext_blocking_n;
wire    ap_str_blocking_n;
wire    ap_int_blocking_n;
reg    ap_ext_blocking_n_reg;
reg    ap_str_blocking_n_reg;
reg    ap_int_blocking_n_reg;

// power-on initialization
initial begin
#0 ap_rst_n_inv = 1'b1;
#0 PixelStream2AXIBursts_U0_ap_start = 1'b0;
#0 ap_sync_reg_Filter2D_U0_ap_ready = 1'b0;
#0 Filter2D_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_AXIBursts2PixelStream8_U0_ap_ready = 1'b0;
#0 AXIBursts2PixelStream8_U0_ap_ready_count = 2'd0;
end

Filter2DKernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
Filter2DKernel_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .coeffs(coeffs),
    .src_V(src_V),
    .width(width),
    .height(height),
    .stride(stride),
    .dst_V(dst_V)
);

Filter2DKernel_gmem1_m_axi #(
    .USER_DW( 256 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ))
Filter2DKernel_gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Filter2D_U0_m_axi_srcCoeffs_ARVALID),
    .I_ARREADY(gmem1_ARREADY),
    .I_ARADDR(Filter2D_U0_m_axi_srcCoeffs_ARADDR),
    .I_ARID(Filter2D_U0_m_axi_srcCoeffs_ARID),
    .I_ARLEN(Filter2D_U0_m_axi_srcCoeffs_ARLEN),
    .I_ARSIZE(Filter2D_U0_m_axi_srcCoeffs_ARSIZE),
    .I_ARLOCK(Filter2D_U0_m_axi_srcCoeffs_ARLOCK),
    .I_ARCACHE(Filter2D_U0_m_axi_srcCoeffs_ARCACHE),
    .I_ARQOS(Filter2D_U0_m_axi_srcCoeffs_ARQOS),
    .I_ARPROT(Filter2D_U0_m_axi_srcCoeffs_ARPROT),
    .I_ARUSER(Filter2D_U0_m_axi_srcCoeffs_ARUSER),
    .I_ARBURST(Filter2D_U0_m_axi_srcCoeffs_ARBURST),
    .I_ARREGION(Filter2D_U0_m_axi_srcCoeffs_ARREGION),
    .I_RVALID(gmem1_RVALID),
    .I_RREADY(Filter2D_U0_m_axi_srcCoeffs_RREADY),
    .I_RDATA(gmem1_RDATA),
    .I_RID(gmem1_RID),
    .I_RUSER(gmem1_RUSER),
    .I_RRESP(gmem1_RRESP),
    .I_RLAST(gmem1_RLAST),
    .I_AWVALID(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWVALID),
    .I_AWREADY(gmem1_AWREADY),
    .I_AWADDR(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWADDR),
    .I_AWID(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWID),
    .I_AWLEN(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWLEN),
    .I_AWSIZE(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWSIZE),
    .I_AWLOCK(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWLOCK),
    .I_AWCACHE(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWCACHE),
    .I_AWQOS(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWQOS),
    .I_AWPROT(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWPROT),
    .I_AWUSER(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWUSER),
    .I_AWBURST(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWBURST),
    .I_AWREGION(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWREGION),
    .I_WVALID(PixelStream2AXIBursts_U0_m_axi_aximm_V_WVALID),
    .I_WREADY(gmem1_WREADY),
    .I_WDATA(PixelStream2AXIBursts_U0_m_axi_aximm_V_WDATA),
    .I_WID(PixelStream2AXIBursts_U0_m_axi_aximm_V_WID),
    .I_WUSER(PixelStream2AXIBursts_U0_m_axi_aximm_V_WUSER),
    .I_WLAST(PixelStream2AXIBursts_U0_m_axi_aximm_V_WLAST),
    .I_WSTRB(PixelStream2AXIBursts_U0_m_axi_aximm_V_WSTRB),
    .I_BVALID(gmem1_BVALID),
    .I_BREADY(PixelStream2AXIBursts_U0_m_axi_aximm_V_BREADY),
    .I_BRESP(gmem1_BRESP),
    .I_BID(gmem1_BID),
    .I_BUSER(gmem1_BUSER)
);

Filter2DKernel_gmem0_m_axi #(
    .USER_DW( 256 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ))
Filter2DKernel_gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARVALID),
    .I_ARREADY(gmem0_ARREADY),
    .I_ARADDR(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARADDR),
    .I_ARID(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARID),
    .I_ARLEN(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARLEN),
    .I_ARSIZE(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARSIZE),
    .I_ARLOCK(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARLOCK),
    .I_ARCACHE(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARCACHE),
    .I_ARQOS(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARQOS),
    .I_ARPROT(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARPROT),
    .I_ARUSER(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARUSER),
    .I_ARBURST(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARBURST),
    .I_ARREGION(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARREGION),
    .I_RVALID(gmem0_RVALID),
    .I_RREADY(AXIBursts2PixelStream8_U0_m_axi_axi_V_RREADY),
    .I_RDATA(gmem0_RDATA),
    .I_RID(gmem0_RID),
    .I_RUSER(gmem0_RUSER),
    .I_RRESP(gmem0_RRESP),
    .I_RLAST(gmem0_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(gmem0_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(gmem0_WREADY),
    .I_WDATA(256'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(32'd0),
    .I_BVALID(gmem0_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(gmem0_BRESP),
    .I_BID(gmem0_BID),
    .I_BUSER(gmem0_BUSER)
);

AXIBursts2PixelStream8 AXIBursts2PixelStream8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIBursts2PixelStream8_U0_ap_start),
    .ap_done(AXIBursts2PixelStream8_U0_ap_done),
    .ap_continue(AXIBursts2PixelStream8_U0_ap_continue),
    .ap_idle(AXIBursts2PixelStream8_U0_ap_idle),
    .ap_ready(AXIBursts2PixelStream8_U0_ap_ready),
    .m_axi_axi_V_AWVALID(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWVALID),
    .m_axi_axi_V_AWREADY(1'b0),
    .m_axi_axi_V_AWADDR(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWADDR),
    .m_axi_axi_V_AWID(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWID),
    .m_axi_axi_V_AWLEN(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWLEN),
    .m_axi_axi_V_AWSIZE(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWSIZE),
    .m_axi_axi_V_AWBURST(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWBURST),
    .m_axi_axi_V_AWLOCK(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWLOCK),
    .m_axi_axi_V_AWCACHE(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWCACHE),
    .m_axi_axi_V_AWPROT(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWPROT),
    .m_axi_axi_V_AWQOS(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWQOS),
    .m_axi_axi_V_AWREGION(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWREGION),
    .m_axi_axi_V_AWUSER(AXIBursts2PixelStream8_U0_m_axi_axi_V_AWUSER),
    .m_axi_axi_V_WVALID(AXIBursts2PixelStream8_U0_m_axi_axi_V_WVALID),
    .m_axi_axi_V_WREADY(1'b0),
    .m_axi_axi_V_WDATA(AXIBursts2PixelStream8_U0_m_axi_axi_V_WDATA),
    .m_axi_axi_V_WSTRB(AXIBursts2PixelStream8_U0_m_axi_axi_V_WSTRB),
    .m_axi_axi_V_WLAST(AXIBursts2PixelStream8_U0_m_axi_axi_V_WLAST),
    .m_axi_axi_V_WID(AXIBursts2PixelStream8_U0_m_axi_axi_V_WID),
    .m_axi_axi_V_WUSER(AXIBursts2PixelStream8_U0_m_axi_axi_V_WUSER),
    .m_axi_axi_V_ARVALID(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARVALID),
    .m_axi_axi_V_ARREADY(gmem0_ARREADY),
    .m_axi_axi_V_ARADDR(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARADDR),
    .m_axi_axi_V_ARID(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARID),
    .m_axi_axi_V_ARLEN(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARLEN),
    .m_axi_axi_V_ARSIZE(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARSIZE),
    .m_axi_axi_V_ARBURST(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARBURST),
    .m_axi_axi_V_ARLOCK(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARLOCK),
    .m_axi_axi_V_ARCACHE(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARCACHE),
    .m_axi_axi_V_ARPROT(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARPROT),
    .m_axi_axi_V_ARQOS(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARQOS),
    .m_axi_axi_V_ARREGION(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARREGION),
    .m_axi_axi_V_ARUSER(AXIBursts2PixelStream8_U0_m_axi_axi_V_ARUSER),
    .m_axi_axi_V_RVALID(gmem0_RVALID),
    .m_axi_axi_V_RREADY(AXIBursts2PixelStream8_U0_m_axi_axi_V_RREADY),
    .m_axi_axi_V_RDATA(gmem0_RDATA),
    .m_axi_axi_V_RLAST(gmem0_RLAST),
    .m_axi_axi_V_RID(gmem0_RID),
    .m_axi_axi_V_RUSER(gmem0_RUSER),
    .m_axi_axi_V_RRESP(gmem0_RRESP),
    .m_axi_axi_V_BVALID(1'b0),
    .m_axi_axi_V_BREADY(AXIBursts2PixelStream8_U0_m_axi_axi_V_BREADY),
    .m_axi_axi_V_BRESP(2'd0),
    .m_axi_axi_V_BID(1'd0),
    .m_axi_axi_V_BUSER(1'd0),
    .axi_V_offset(src_V),
    .width(width),
    .height(height),
    .stride(stride),
    .stream_V_din(AXIBursts2PixelStream8_U0_stream_V_din),
    .stream_V_full_n(src_pixels_V_full_n),
    .stream_V_write(AXIBursts2PixelStream8_U0_stream_V_write),
    .width_out_din(AXIBursts2PixelStream8_U0_width_out_din),
    .width_out_full_n(width_c_full_n),
    .width_out_write(AXIBursts2PixelStream8_U0_width_out_write),
    .height_out_din(AXIBursts2PixelStream8_U0_height_out_din),
    .height_out_full_n(height_c_full_n),
    .height_out_write(AXIBursts2PixelStream8_U0_height_out_write),
    .stride_out_din(AXIBursts2PixelStream8_U0_stride_out_din),
    .stride_out_full_n(stride_c_full_n),
    .stride_out_write(AXIBursts2PixelStream8_U0_stride_out_write),
    .coeffs(coeffs),
    .dst_V(dst_V),
    .coeffs_out_din(AXIBursts2PixelStream8_U0_coeffs_out_din),
    .coeffs_out_full_n(coeffs_c_full_n),
    .coeffs_out_write(AXIBursts2PixelStream8_U0_coeffs_out_write),
    .dst_V_out_din(AXIBursts2PixelStream8_U0_dst_V_out_din),
    .dst_V_out_full_n(dst_V_c_full_n),
    .dst_V_out_write(AXIBursts2PixelStream8_U0_dst_V_out_write),
    .ap_ext_blocking_n(AXIBursts2PixelStream8_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(AXIBursts2PixelStream8_U0_ap_str_blocking_n),
    .ap_int_blocking_n(AXIBursts2PixelStream8_U0_ap_int_blocking_n)
);

Filter2D Filter2D_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter2D_U0_ap_start),
    .ap_done(Filter2D_U0_ap_done),
    .ap_continue(Filter2D_U0_ap_continue),
    .ap_idle(Filter2D_U0_ap_idle),
    .ap_ready(Filter2D_U0_ap_ready),
    .m_axi_srcCoeffs_AWVALID(Filter2D_U0_m_axi_srcCoeffs_AWVALID),
    .m_axi_srcCoeffs_AWREADY(1'b0),
    .m_axi_srcCoeffs_AWADDR(Filter2D_U0_m_axi_srcCoeffs_AWADDR),
    .m_axi_srcCoeffs_AWID(Filter2D_U0_m_axi_srcCoeffs_AWID),
    .m_axi_srcCoeffs_AWLEN(Filter2D_U0_m_axi_srcCoeffs_AWLEN),
    .m_axi_srcCoeffs_AWSIZE(Filter2D_U0_m_axi_srcCoeffs_AWSIZE),
    .m_axi_srcCoeffs_AWBURST(Filter2D_U0_m_axi_srcCoeffs_AWBURST),
    .m_axi_srcCoeffs_AWLOCK(Filter2D_U0_m_axi_srcCoeffs_AWLOCK),
    .m_axi_srcCoeffs_AWCACHE(Filter2D_U0_m_axi_srcCoeffs_AWCACHE),
    .m_axi_srcCoeffs_AWPROT(Filter2D_U0_m_axi_srcCoeffs_AWPROT),
    .m_axi_srcCoeffs_AWQOS(Filter2D_U0_m_axi_srcCoeffs_AWQOS),
    .m_axi_srcCoeffs_AWREGION(Filter2D_U0_m_axi_srcCoeffs_AWREGION),
    .m_axi_srcCoeffs_AWUSER(Filter2D_U0_m_axi_srcCoeffs_AWUSER),
    .m_axi_srcCoeffs_WVALID(Filter2D_U0_m_axi_srcCoeffs_WVALID),
    .m_axi_srcCoeffs_WREADY(1'b0),
    .m_axi_srcCoeffs_WDATA(Filter2D_U0_m_axi_srcCoeffs_WDATA),
    .m_axi_srcCoeffs_WSTRB(Filter2D_U0_m_axi_srcCoeffs_WSTRB),
    .m_axi_srcCoeffs_WLAST(Filter2D_U0_m_axi_srcCoeffs_WLAST),
    .m_axi_srcCoeffs_WID(Filter2D_U0_m_axi_srcCoeffs_WID),
    .m_axi_srcCoeffs_WUSER(Filter2D_U0_m_axi_srcCoeffs_WUSER),
    .m_axi_srcCoeffs_ARVALID(Filter2D_U0_m_axi_srcCoeffs_ARVALID),
    .m_axi_srcCoeffs_ARREADY(gmem1_ARREADY),
    .m_axi_srcCoeffs_ARADDR(Filter2D_U0_m_axi_srcCoeffs_ARADDR),
    .m_axi_srcCoeffs_ARID(Filter2D_U0_m_axi_srcCoeffs_ARID),
    .m_axi_srcCoeffs_ARLEN(Filter2D_U0_m_axi_srcCoeffs_ARLEN),
    .m_axi_srcCoeffs_ARSIZE(Filter2D_U0_m_axi_srcCoeffs_ARSIZE),
    .m_axi_srcCoeffs_ARBURST(Filter2D_U0_m_axi_srcCoeffs_ARBURST),
    .m_axi_srcCoeffs_ARLOCK(Filter2D_U0_m_axi_srcCoeffs_ARLOCK),
    .m_axi_srcCoeffs_ARCACHE(Filter2D_U0_m_axi_srcCoeffs_ARCACHE),
    .m_axi_srcCoeffs_ARPROT(Filter2D_U0_m_axi_srcCoeffs_ARPROT),
    .m_axi_srcCoeffs_ARQOS(Filter2D_U0_m_axi_srcCoeffs_ARQOS),
    .m_axi_srcCoeffs_ARREGION(Filter2D_U0_m_axi_srcCoeffs_ARREGION),
    .m_axi_srcCoeffs_ARUSER(Filter2D_U0_m_axi_srcCoeffs_ARUSER),
    .m_axi_srcCoeffs_RVALID(gmem1_RVALID),
    .m_axi_srcCoeffs_RREADY(Filter2D_U0_m_axi_srcCoeffs_RREADY),
    .m_axi_srcCoeffs_RDATA(gmem1_RDATA),
    .m_axi_srcCoeffs_RLAST(gmem1_RLAST),
    .m_axi_srcCoeffs_RID(gmem1_RID),
    .m_axi_srcCoeffs_RUSER(gmem1_RUSER),
    .m_axi_srcCoeffs_RRESP(gmem1_RRESP),
    .m_axi_srcCoeffs_BVALID(1'b0),
    .m_axi_srcCoeffs_BREADY(Filter2D_U0_m_axi_srcCoeffs_BREADY),
    .m_axi_srcCoeffs_BRESP(2'd0),
    .m_axi_srcCoeffs_BID(1'd0),
    .m_axi_srcCoeffs_BUSER(1'd0),
    .srcCoeffs_offset_dout(coeffs_c_dout),
    .srcCoeffs_offset_empty_n(coeffs_c_empty_n),
    .srcCoeffs_offset_read(Filter2D_U0_srcCoeffs_offset_read),
    .srcImg_V_dout(src_pixels_V_dout),
    .srcImg_V_empty_n(src_pixels_V_empty_n),
    .srcImg_V_read(Filter2D_U0_srcImg_V_read),
    .width_dout(width_c_dout),
    .width_empty_n(width_c_empty_n),
    .width_read(Filter2D_U0_width_read),
    .height_dout(height_c_dout),
    .height_empty_n(height_c_empty_n),
    .height_read(Filter2D_U0_height_read),
    .dstImg_V_din(Filter2D_U0_dstImg_V_din),
    .dstImg_V_full_n(dst_pixels_V_full_n),
    .dstImg_V_write(Filter2D_U0_dstImg_V_write),
    .width_out_din(Filter2D_U0_width_out_din),
    .width_out_full_n(width_c1_full_n),
    .width_out_write(Filter2D_U0_width_out_write),
    .height_out_din(Filter2D_U0_height_out_din),
    .height_out_full_n(height_c2_full_n),
    .height_out_write(Filter2D_U0_height_out_write),
    .ap_ext_blocking_n(Filter2D_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(Filter2D_U0_ap_str_blocking_n),
    .ap_int_blocking_n(Filter2D_U0_ap_int_blocking_n)
);

PixelStream2AXIBursts PixelStream2AXIBursts_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(PixelStream2AXIBursts_U0_ap_start),
    .ap_done(PixelStream2AXIBursts_U0_ap_done),
    .ap_continue(PixelStream2AXIBursts_U0_ap_continue),
    .ap_idle(PixelStream2AXIBursts_U0_ap_idle),
    .ap_ready(PixelStream2AXIBursts_U0_ap_ready),
    .stream_V_dout(dst_pixels_V_dout),
    .stream_V_empty_n(dst_pixels_V_empty_n),
    .stream_V_read(PixelStream2AXIBursts_U0_stream_V_read),
    .width_dout(width_c1_dout),
    .width_empty_n(width_c1_empty_n),
    .width_read(PixelStream2AXIBursts_U0_width_read),
    .height_dout(height_c2_dout),
    .height_empty_n(height_c2_empty_n),
    .height_read(PixelStream2AXIBursts_U0_height_read),
    .stride_dout(stride_c_dout),
    .stride_empty_n(stride_c_empty_n),
    .stride_read(PixelStream2AXIBursts_U0_stride_read),
    .m_axi_aximm_V_AWVALID(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWVALID),
    .m_axi_aximm_V_AWREADY(gmem1_AWREADY),
    .m_axi_aximm_V_AWADDR(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWADDR),
    .m_axi_aximm_V_AWID(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWID),
    .m_axi_aximm_V_AWLEN(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWLEN),
    .m_axi_aximm_V_AWSIZE(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWSIZE),
    .m_axi_aximm_V_AWBURST(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWBURST),
    .m_axi_aximm_V_AWLOCK(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWLOCK),
    .m_axi_aximm_V_AWCACHE(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWCACHE),
    .m_axi_aximm_V_AWPROT(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWPROT),
    .m_axi_aximm_V_AWQOS(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWQOS),
    .m_axi_aximm_V_AWREGION(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWREGION),
    .m_axi_aximm_V_AWUSER(PixelStream2AXIBursts_U0_m_axi_aximm_V_AWUSER),
    .m_axi_aximm_V_WVALID(PixelStream2AXIBursts_U0_m_axi_aximm_V_WVALID),
    .m_axi_aximm_V_WREADY(gmem1_WREADY),
    .m_axi_aximm_V_WDATA(PixelStream2AXIBursts_U0_m_axi_aximm_V_WDATA),
    .m_axi_aximm_V_WSTRB(PixelStream2AXIBursts_U0_m_axi_aximm_V_WSTRB),
    .m_axi_aximm_V_WLAST(PixelStream2AXIBursts_U0_m_axi_aximm_V_WLAST),
    .m_axi_aximm_V_WID(PixelStream2AXIBursts_U0_m_axi_aximm_V_WID),
    .m_axi_aximm_V_WUSER(PixelStream2AXIBursts_U0_m_axi_aximm_V_WUSER),
    .m_axi_aximm_V_ARVALID(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARVALID),
    .m_axi_aximm_V_ARREADY(1'b0),
    .m_axi_aximm_V_ARADDR(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARADDR),
    .m_axi_aximm_V_ARID(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARID),
    .m_axi_aximm_V_ARLEN(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARLEN),
    .m_axi_aximm_V_ARSIZE(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARSIZE),
    .m_axi_aximm_V_ARBURST(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARBURST),
    .m_axi_aximm_V_ARLOCK(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARLOCK),
    .m_axi_aximm_V_ARCACHE(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARCACHE),
    .m_axi_aximm_V_ARPROT(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARPROT),
    .m_axi_aximm_V_ARQOS(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARQOS),
    .m_axi_aximm_V_ARREGION(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARREGION),
    .m_axi_aximm_V_ARUSER(PixelStream2AXIBursts_U0_m_axi_aximm_V_ARUSER),
    .m_axi_aximm_V_RVALID(1'b0),
    .m_axi_aximm_V_RREADY(PixelStream2AXIBursts_U0_m_axi_aximm_V_RREADY),
    .m_axi_aximm_V_RDATA(256'd0),
    .m_axi_aximm_V_RLAST(1'b0),
    .m_axi_aximm_V_RID(1'd0),
    .m_axi_aximm_V_RUSER(1'd0),
    .m_axi_aximm_V_RRESP(2'd0),
    .m_axi_aximm_V_BVALID(gmem1_BVALID),
    .m_axi_aximm_V_BREADY(PixelStream2AXIBursts_U0_m_axi_aximm_V_BREADY),
    .m_axi_aximm_V_BRESP(gmem1_BRESP),
    .m_axi_aximm_V_BID(gmem1_BID),
    .m_axi_aximm_V_BUSER(gmem1_BUSER),
    .aximm_V_offset_dout(dst_V_c_dout),
    .aximm_V_offset_empty_n(dst_V_c_empty_n),
    .aximm_V_offset_read(PixelStream2AXIBursts_U0_aximm_V_offset_read),
    .ap_ext_blocking_n(PixelStream2AXIBursts_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(PixelStream2AXIBursts_U0_ap_str_blocking_n),
    .ap_int_blocking_n(PixelStream2AXIBursts_U0_ap_int_blocking_n)
);

fifo_w8_d64_A src_pixels_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIBursts2PixelStream8_U0_stream_V_din),
    .if_full_n(src_pixels_V_full_n),
    .if_write(AXIBursts2PixelStream8_U0_stream_V_write),
    .if_dout(src_pixels_V_dout),
    .if_empty_n(src_pixels_V_empty_n),
    .if_read(Filter2D_U0_srcImg_V_read)
);

fifo_w32_d1_A width_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIBursts2PixelStream8_U0_width_out_din),
    .if_full_n(width_c_full_n),
    .if_write(AXIBursts2PixelStream8_U0_width_out_write),
    .if_dout(width_c_dout),
    .if_empty_n(width_c_empty_n),
    .if_read(Filter2D_U0_width_read)
);

fifo_w32_d1_A height_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIBursts2PixelStream8_U0_height_out_din),
    .if_full_n(height_c_full_n),
    .if_write(AXIBursts2PixelStream8_U0_height_out_write),
    .if_dout(height_c_dout),
    .if_empty_n(height_c_empty_n),
    .if_read(Filter2D_U0_height_read)
);

fifo_w32_d2_A stride_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIBursts2PixelStream8_U0_stride_out_din),
    .if_full_n(stride_c_full_n),
    .if_write(AXIBursts2PixelStream8_U0_stride_out_write),
    .if_dout(stride_c_dout),
    .if_empty_n(stride_c_empty_n),
    .if_read(PixelStream2AXIBursts_U0_stride_read)
);

fifo_w64_d1_A coeffs_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIBursts2PixelStream8_U0_coeffs_out_din),
    .if_full_n(coeffs_c_full_n),
    .if_write(AXIBursts2PixelStream8_U0_coeffs_out_write),
    .if_dout(coeffs_c_dout),
    .if_empty_n(coeffs_c_empty_n),
    .if_read(Filter2D_U0_srcCoeffs_offset_read)
);

fifo_w64_d2_A dst_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIBursts2PixelStream8_U0_dst_V_out_din),
    .if_full_n(dst_V_c_full_n),
    .if_write(AXIBursts2PixelStream8_U0_dst_V_out_write),
    .if_dout(dst_V_c_dout),
    .if_empty_n(dst_V_c_empty_n),
    .if_read(PixelStream2AXIBursts_U0_aximm_V_offset_read)
);

fifo_w8_d64_A dst_pixels_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_U0_dstImg_V_din),
    .if_full_n(dst_pixels_V_full_n),
    .if_write(Filter2D_U0_dstImg_V_write),
    .if_dout(dst_pixels_V_dout),
    .if_empty_n(dst_pixels_V_empty_n),
    .if_read(PixelStream2AXIBursts_U0_stream_V_read)
);

fifo_w32_d1_A width_c1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_U0_width_out_din),
    .if_full_n(width_c1_full_n),
    .if_write(Filter2D_U0_width_out_write),
    .if_dout(width_c1_dout),
    .if_empty_n(width_c1_empty_n),
    .if_read(PixelStream2AXIBursts_U0_width_read)
);

fifo_w32_d1_A height_c2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter2D_U0_height_out_din),
    .if_full_n(height_c2_full_n),
    .if_write(Filter2D_U0_height_out_write),
    .if_dout(height_c2_dout),
    .if_empty_n(height_c2_empty_n),
    .if_read(PixelStream2AXIBursts_U0_height_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        PixelStream2AXIBursts_U0_ap_start <= 1'b0;
    end else begin
        PixelStream2AXIBursts_U0_ap_start <= 1'b1;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_AXIBursts2PixelStream8_U0_ap_ready <= 1'b0;
    end else begin
        if ((1'b1 == (ap_start & ap_sync_ready))) begin
            ap_sync_reg_AXIBursts2PixelStream8_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIBursts2PixelStream8_U0_ap_ready <= ap_sync_AXIBursts2PixelStream8_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Filter2D_U0_ap_ready <= 1'b0;
    end else begin
        if ((1'b1 == (ap_start & ap_sync_ready))) begin
            ap_sync_reg_Filter2D_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Filter2D_U0_ap_ready <= ap_sync_Filter2D_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sync_ready) & (AXIBursts2PixelStream8_U0_ap_ready == 1'b0))) begin
        AXIBursts2PixelStream8_U0_ap_ready_count <= (AXIBursts2PixelStream8_U0_ap_ready_count - 2'd1);
    end else if (((1'b0 == ap_sync_ready) & (1'b1 == AXIBursts2PixelStream8_U0_ap_ready))) begin
        AXIBursts2PixelStream8_U0_ap_ready_count <= (AXIBursts2PixelStream8_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == Filter2D_U0_ap_ready) & (1'b1 == ap_sync_ready))) begin
        Filter2D_U0_ap_ready_count <= (Filter2D_U0_ap_ready_count - 2'd1);
    end else if (((1'b1 == Filter2D_U0_ap_ready) & (1'b0 == ap_sync_ready))) begin
        Filter2D_U0_ap_ready_count <= (Filter2D_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    ap_ext_blocking_n_reg <= ap_ext_blocking_n;
end

always @ (posedge ap_clk) begin
    ap_int_blocking_n_reg <= ap_int_blocking_n;
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    ap_str_blocking_n_reg <= ap_str_blocking_n;
end

always @ (*) begin
    if (((1'b0 == ap_ext_blocking_n_reg) & (1'b1 == ap_ext_blocking_n))) begin
        stall_done_ext = 1'b1;
    end else begin
        stall_done_ext = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_int_blocking_n_reg) & (1'b1 == ap_int_blocking_n))) begin
        stall_done_int = 1'b1;
    end else begin
        stall_done_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_str_blocking_n_reg) & (1'b1 == ap_str_blocking_n))) begin
        stall_done_str = 1'b1;
    end else begin
        stall_done_str = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ext_blocking_n_reg) & (1'b0 == ap_ext_blocking_n))) begin
        stall_start_ext = 1'b1;
    end else begin
        stall_start_ext = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_int_blocking_n_reg) & (1'b0 == ap_int_blocking_n))) begin
        stall_start_int = 1'b1;
    end else begin
        stall_start_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_str_blocking_n_reg) & (1'b0 == ap_str_blocking_n))) begin
        stall_start_str = 1'b1;
    end else begin
        stall_start_str = 1'b0;
    end
end

assign AXIBursts2PixelStream8_U0_ap_continue = 1'b1;

assign AXIBursts2PixelStream8_U0_ap_start = (ap_start & (ap_sync_reg_AXIBursts2PixelStream8_U0_ap_ready ^ 1'b1));

assign AXIBursts2PixelStream8_U0_start_full_n = 1'b0;

assign AXIBursts2PixelStream8_U0_start_write = 1'b0;

assign Filter2D_U0_ap_continue = 1'b1;

assign Filter2D_U0_ap_start = (ap_start & (ap_sync_reg_Filter2D_U0_ap_ready ^ 1'b1));

assign Filter2D_U0_start_full_n = 1'b0;

assign Filter2D_U0_start_write = 1'b0;

assign PixelStream2AXIBursts_U0_ap_continue = 1'b1;

assign PixelStream2AXIBursts_U0_start_full_n = 1'b0;

assign PixelStream2AXIBursts_U0_start_write = 1'b0;

assign ap_done = PixelStream2AXIBursts_U0_ap_done;

assign ap_ext_blocking_cur_n = 1'b1;

assign ap_ext_blocking_n = (ap_ext_blocking_cur_n & ap_ext_blocking_sub_n);

assign ap_ext_blocking_sub_n = (AXIBursts2PixelStream8_U0_ap_ext_blocking_n & Filter2D_U0_ap_ext_blocking_n & PixelStream2AXIBursts_U0_ap_ext_blocking_n);

assign ap_idle = (AXIBursts2PixelStream8_U0_ap_idle & Filter2D_U0_ap_idle & PixelStream2AXIBursts_U0_ap_idle);

assign ap_int_blocking_cur_n = 1'b1;

assign ap_int_blocking_n = (ap_int_blocking_cur_n & ap_int_blocking_sub_n);

assign ap_int_blocking_sub_n = (AXIBursts2PixelStream8_U0_ap_int_blocking_n & Filter2D_U0_ap_int_blocking_n & PixelStream2AXIBursts_U0_ap_int_blocking_n);

assign ap_ready = ap_sync_ready;

assign ap_str_blocking_cur_n = 1'b1;

assign ap_str_blocking_n = (ap_str_blocking_cur_n & ap_str_blocking_sub_n);

assign ap_str_blocking_sub_n = (AXIBursts2PixelStream8_U0_ap_str_blocking_n & Filter2D_U0_ap_str_blocking_n & PixelStream2AXIBursts_U0_ap_str_blocking_n);

assign ap_sync_AXIBursts2PixelStream8_U0_ap_ready = (AXIBursts2PixelStream8_U0_ap_ready | ap_sync_reg_AXIBursts2PixelStream8_U0_ap_ready);

assign ap_sync_Filter2D_U0_ap_ready = (Filter2D_U0_ap_ready | ap_sync_reg_Filter2D_U0_ap_ready);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = PixelStream2AXIBursts_U0_ap_done;

assign ap_sync_ready = (ap_sync_Filter2D_U0_ap_ready & ap_sync_AXIBursts2PixelStream8_U0_ap_ready);

endmodule //Filter2DKernel
